name: task_manager
description: A task management app with Firebase integration and CRUD functionality

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.6.0         # Core Firebase package for initialization
  firebase_auth: ^4.5.0         # Firebase authentication for user login
  cloud_firestore: ^4.7.0       # Firestore for real-time database operations
  provider: ^6.0.4              # State management solution

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true